# Generated by Django 4.0.4 on 2022-04-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=100)),
                (
                    "book_type",
                    models.CharField(
                        choices=[
                            ("Sci-tech", "Sci-tech"),
                            ("Magazine", "Magazine"),
                            ("Comic", "Comic"),
                            ("Classic", "Classic"),
                            ("Horror", "Horror"),
                        ],
                        max_length=140,
                    ),
                ),
                ("ISBN", models.CharField(max_length=255)),
                ("year_published", models.CharField(max_length=4)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("no_of_pages", models.PositiveIntegerField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
