# Generated by Django 4.0.4 on 2022-04-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
