# Generated by Django 4.0.4 on 2022-04-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_book_created_at_alter_book_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={},
        ),
        migrations.RemoveField(
            model_name="book",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="book",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="book",
            name="updated_at",
        ),
    ]
